### ISSUE TITLE
Data Visualization Website

### ISSUE THREAD

**Issue by ethan92429** [ethan92429/POST#10]
Here is the current [website](http://map.wash4all.org/) with the WASH4ALL data... as you can see there are only a handful of plants that actually record data, and the data is limited to turbidity/flow rates over time. Would be interesting to be able to overlay different plant turbidities on top of one another, and to get raw turbidity v. PACl dose charts for each plant. Make a wireframe to initiate discussion about which data to display and how. Walker and Jon, do either of you have suggestions for which data is important to display?

**Comment by wngrimshaw** [comment]
The coagulant to raw water turbidity is an important parameter, but we need to make sure we are still promoting the use of the lowest effective dose rather than just the lowest permissible dose. Some plants are already quite paranoid about chemical savings with less emphasis on water quality.
We would like to enable operators to report when filters are backwashed. We are also working on operation and maintenance checklists for the plants. This information is less important to visualize on the website but is something operators should report in the future. Items would include cleaning of chemical system, cleaning of flocculation channels and sedimentation tanks, backwash, measurements of pH and chlorine residual in the first and last taps of the town.

**Comment by iamchriskelley** [comment]
There seems to be some confusion here. The page Ethan referenced is the overview map for the monitoring system -- designed to provide a data-light visualization of the current performance of a system. The full monitoring page, [here](http://monitor.wash4all.org/), does indeed chart coagulant dosage, as well as raw/settled/filtered turbidity, chlorine, flow rate, and turbidity removal.
